# Generated by Django 4.2.4 on 2023-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_diary', '0003_diary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='what_I_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='what_should_be_changed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
